name: Animal Farm NodeJS CI

on:

  push:

    branches:

      - main

  pull_request:

    branches:

      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository

      uses: actions/checkout@v2

    - name: Use Node.js

      uses: actions/setup-node@v1

      with:

        node-version: '16.x'

    - name: Run Yarn 

      run: npm intsall

    - name: Run tests

      run: npm run-script build
